/*
 * Copyright 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import ratpack.gradle.WriteTestConfig

import io.freefair.gradle.plugins.jsass.SassCompile

import static org.apache.commons.io.FileUtils.copyURLToFile
import static org.apache.commons.lang3.SystemUtils.*

buildscript {
  repositories {
    mavenCentral()
    gradlePluginPortal()
    maven { url 'https://jitpack.io' }
  }
  dependencies {
    classpath 'com.github.jengelman.gradle.plugins:shadow:5.1.0'
    classpath 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.1'
    classpath "io.freefair.gradle:jsass-plugin:5.3.0"
    // Use the master version of gradle-js-plugin since it fixes a Gradle 6 deprecation (from JitPack.io)
    classpath "com.github.eriwen:gradle-js-plugin:d15f4ae"
    classpath "com.google.javascript:closure-compiler:v20150315"
    classpath "com.google.cloud.tools.jib:com.google.cloud.tools.jib.gradle.plugin:3.4.5", {
      exclude group: "com.google.collections"
      exclude group: "com.google.guava"
    }
  }
}

apply from: "$rootDir/gradle/javaModule.gradle"
apply plugin: "io.ratpack.ratpack-java"
apply plugin: "org.gradle.groovy"
apply plugin: 'com.github.johnrengelman.shadow'
apply plugin: 'io.freefair.jsass-base'
apply plugin: 'com.google.cloud.tools.jib'

repositories {
  mavenCentral()
}

ext {
  manualVersions = [
    "1.0.0",
    "1.1.0", "1.1.1",
    "1.2.0",
    "1.3.0", "1.3.1", "1.3.2", "1.3.3",
    "1.4.0", "1.4.1", "1.4.2", "1.4.3", "1.4.4", "1.4.5", "1.4.6",
    "1.5.0", "1.5.1", "1.5.2", "1.5.3", "1.5.4",
    "1.6.0", "1.6.1",
    "1.7.0", "1.7.1", "1.7.2", "1.7.3", "1.7.4", "1.7.5", "1.7.6",
    "1.8.0", "1.8.1", "1.8.2",
    "1.9.0"
  ]

  if (!isHeroku && !isCi) {
    logger.info("Only including latest manual in site due to this being a development build.")
    manualVersions = [manualVersions.last()]
  }
}

configurations {
  latestManual {
    // Force resolve of latest snapshot
    resolutionStrategy {
      cacheChangingModulesFor 0, 'seconds'
    }
  }
  newrelicAgent {}
  browserTestCompile.extendsFrom testCompile
  browserTestRuntime.extendsFrom testRuntime
  providedRuntime
  runtime.extendsFrom providedRuntime
  manualVersions.each {
    delegate."manual-$it"
  }
  runtime.exclude module: "slf4j-simple"
}

ext {
  generatedTestResourcesDir = file("$buildDir/generated-test-resources")
}

sourceSets {
  browserTest {
    compileClasspath += (main.output + test.output)
    runtimeClasspath += (main.output + test.output)
  }
}

dependencies {
  compile project(":ratpack-groovy")
  compile project(":ratpack-dropwizard-metrics")
  compile project(":ratpack-remote")
  compile project(":ratpack-rx2")
  compile project(":ratpack-newrelic")
  compile "org.pegdown:pegdown:${commonVersions.pegdown}"

  runtime "org.apache.logging.log4j:log4j-slf4j-impl:${commonVersions.log4j}", {
    exclude group: "org.slf4j", module: "slf4j-api"
  }
  runtime "org.apache.logging.log4j:log4j-api:${commonVersions.log4j}"
  runtime "org.apache.logging.log4j:log4j-core:${commonVersions.log4j}"
  runtime 'com.lmax:disruptor:3.4.2'

  testCompile project(":ratpack-groovy-test")
  testCompile project(":ratpack-remote-test")
  testCompile project(":ratpack-test-internal")
  testCompile commonDependencies.spock
  testCompile 'org.jsoup:jsoup:1.8.1'
  latestManual isHeroku ? "io.ratpack:ratpack-manual:$version" : project(path: ":ratpack-manual", configuration: "zip")

  browserTestCompile("org.gebish:geb-spock:2.1") {
    exclude group: "org.codehaus.groovy", module: "groovy-all"
    exclude group: "junit", module: "junit"
  }
  browserTestCompile "org.seleniumhq.selenium:selenium-chrome-driver:2.45.0", {
    exclude module: 'guava'
    exclude group: "cglib", module: "cglib-nodep"
  }

  manualVersions.each {
    delegate."manual-$it" "io.ratpack:ratpack-manual:$it@zip"
  }

  newrelicAgent "com.newrelic.agent.java:newrelic-agent:${commonVersions.newrelic}"
}

mainClassName = 'ratpack.site.SiteMain'

tasks.withType(Zip) {
  zip64 = true
}

jib {
  from {
    image = "eclipse-temurin:11"
  }
  container {
    ports = ['5050']
  }
}

task compileSass(type: SassCompile) {
  doFirst { destinationDir.get().asFile.deleteDir() }
  source = "src/assets/sass"
  includePaths.from "$rootDir/shared-web-assets/sass"
  includePaths.from "$rootDir/shared-web-assets"
  destinationDir = file("build/assets/css")
}

task jsAll(type: com.eriwen.gradle.js.tasks.CombineJsTask) {
  source = [
    "${rootDir}/shared-web-assets/js/modernizr.js",
    "${rootDir}/shared-web-assets/js/prism.js",
  ]
  dest = file("${buildDir}/assets/js/all.min.js")
}

task downloadChromeDriver {
  def version = "2.10"
  inputs.property("version", version)

  def webdriverOs
  if (IS_OS_MAC) {
    webdriverOs = 'mac32'
  } else if (IS_OS_LINUX) {
    webdriverOs = 'linux64'
  } else if (IS_OS_WINDOWS) {
    webdriverOs = 'win32'
  }

  def output = new File(gradle.gradleUserHomeDir, "chromedriver-${version}.zip")
  outputs.file output

  onlyIf {
    !output.exists()
  }
  doLast {
    copyURLToFile(new URL("http://chromedriver.storage.googleapis.com/${version}/chromedriver_${webdriverOs}.zip"), output)
  }
}

task unzipChromeDriver(type: Copy) {
  dependsOn downloadChromeDriver
  from(zipTree(downloadChromeDriver.outputs.files.singleFile))
  into new File(buildDir, "webdriver/driver")
}

task configureWriteTestConfig {
  dependsOn unzipChromeDriver
  doLast {
    if (!isSnapCi) {
      writeTestConfig.testProperties.putAll(
        "chromedriver.path": fileTree(unzipChromeDriver.outputs.files.singleFile).singleFile.absolutePath
      )
    }
  }
}

task browserTest(type: Test) {
//  dependsOn assetCompile
  classpath = sourceSets.browserTest.runtimeClasspath
  systemProperty "ratpack.development", "true"
  shouldRunAfter test
  testLogging {
    showStandardStreams true
  }
}

task writeTestConfig(type: WriteTestConfig) {
  dependsOn configureWriteTestConfig
  generatedTestResourcesDir = project.generatedTestResourcesDir

  testProperties.putAll(
    manualVersions: manualVersions.join(','),
    currentVersion: version
  )
}

sourceSets.test.resources.srcDir generatedTestResourcesDir

processTestResources.dependsOn writeTestConfig

processResources {
  inputs.files configurations.latestManual
  into "manual/" + version - "-SNAPSHOT", {
    from { zipTree(configurations.latestManual.singleFile) }
  }
  def configureManualExtraction = { configuration, label ->
    inputs.files configuration
    into "manual/$label", {
      from { zipTree(configuration.singleFile) }
    }
  }

  manualVersions.each {
    configureManualExtraction(configurations["manual-$it"], it)
  }

  into("public") {
    from compileSass
    from jsAll

    [
      "": ["src/assets/images", "src/assets/css"],
      images: ["$rootDir/shared-web-assets/images"],
      fonts: ["$rootDir/shared-web-assets/fonts"]
    ].each { destination, source ->
      if (destination) {
        into("public/$destination") {
          from(source)
        }
      } else {
        into("public") {
          from(source)
        }
      }
    }
  }
}

distributions.main.contents {
  from "src/heroku"
  into("newrelic") {
    from({ configurations.newrelicAgent }) {
      rename { "agent.jar" }
    }
    from "src/newrelic"
  }
}

distTar {
  compression = Compression.GZIP
  version = null
}

run.ext.set("ratpack.flattenClassloaders", true)

distZip {
  enabled = false
}
